//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woningpaspoort.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Woningpaspoort.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add house.
        /// </summary>
        internal static string AddHouse {
            get {
                return ResourceManager.GetString("AddHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addition.
        /// </summary>
        internal static string Addition {
            get {
                return ResourceManager.GetString("Addition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address information.
        /// </summary>
        internal static string AddressInformation {
            get {
                return ResourceManager.GetString("AddressInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin portal.
        /// </summary>
        internal static string AdminPortal {
            get {
                return ResourceManager.GetString("AdminPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build year.
        /// </summary>
        internal static string BuildYear {
            get {
                return ResourceManager.GetString("BuildYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex.
        /// </summary>
        internal static string Complex {
            get {
                return ResourceManager.GetString("Complex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer information.
        /// </summary>
        internal static string CustomerInformation {
            get {
                return ResourceManager.GetString("CustomerInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daeb.
        /// </summary>
        internal static string Daeb {
            get {
                return ResourceManager.GetString("Daeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document has been succesfully added.
        /// </summary>
        internal static string DocumentCreated {
            get {
                return ResourceManager.GetString("DocumentCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        internal static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Externalcode.
        /// </summary>
        internal static string ExternalCode {
            get {
                return ResourceManager.GetString("ExternalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra information.
        /// </summary>
        internal static string ExtraInformation {
            get {
                return ResourceManager.GetString("ExtraInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        internal static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House has been succesfully created.
        /// </summary>
        internal static string HouseCreated {
            get {
                return ResourceManager.GetString("HouseCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Houses.
        /// </summary>
        internal static string Houses {
            get {
                return ResourceManager.GetString("Houses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image has been succesfully added.
        /// </summary>
        internal static string ImageCreated {
            get {
                return ResourceManager.GetString("ImageCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language has been changed to English.
        /// </summary>
        internal static string LanguageChangedToEN {
            get {
                return ResourceManager.GetString("LanguageChangedToEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language has been changed to Dutch.
        /// </summary>
        internal static string LanguageChangedToNL {
            get {
                return ResourceManager.GetString("LanguageChangedToNL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a house first.
        /// </summary>
        internal static string NoHouseSelected {
            get {
                return ResourceManager.GetString("NoHouseSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        internal static string Photos {
            get {
                return ResourceManager.GetString("Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick youre documents.
        /// </summary>
        internal static string PickDocument {
            get {
                return ResourceManager.GetString("PickDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick your images.
        /// </summary>
        internal static string PickImage {
            get {
                return ResourceManager.GetString("PickImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicecontract.
        /// </summary>
        internal static string ServiceContract {
            get {
                return ResourceManager.GetString("ServiceContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serviceorders.
        /// </summary>
        internal static string ServiceOrders {
            get {
                return ResourceManager.GetString("ServiceOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        internal static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail.
        /// </summary>
        internal static string Thumbnail {
            get {
                return ResourceManager.GetString("Thumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Till.
        /// </summary>
        internal static string Till {
            get {
                return ResourceManager.GetString("Till", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zipcode.
        /// </summary>
        internal static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
